name: Deploy Snapshots

on:
  push:
    branches: [ 'master' ]
  workflow_dispatch:
  repository_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8
        cache: 'maven'
        server-id: central
        server-username: SONATYPE_USERNAME
        server-password: SONATYPE_PASSWORD

    - name: Deploy snapshot
      run: mvn -B deploy --file pom.xml
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

    - name: Deploy to ami
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://bamboo-ci.pih-emr.org/rest/api/latest/queue/OMRS-DEPLOYAMI'
        method: 'POST'
        bearerToken: ${{ secrets.PIH_BAMBOO_API_KEY }}
        customHeaders: '{"Accept": "application/json"}'
        retry: 10
        retryWait: 60000

    - name: Deploy to hum-ci
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://bamboo-ci.pih-emr.org/rest/api/latest/queue/OMRS-DEPLOYHUMCI'
        method: 'POST'
        bearerToken: ${{ secrets.PIH_BAMBOO_API_KEY }}
        customHeaders: '{"Accept": "application/json"}'
        retry: 10
        retryWait: 60000

    - name: Deploy to ci
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://bamboo-ci.pih-emr.org/rest/api/latest/queue/OMRS-DEPLOYCI'
        method: 'POST'
        bearerToken: ${{ secrets.PIH_BAMBOO_API_KEY }}
        customHeaders: '{"Accept": "application/json"}'
        retry: 10
        retryWait: 60000

    - name: Deploy to haitihivtest
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://bamboo-ci.pih-emr.org/rest/api/latest/queue/OMRS-DEPLOYHAITIHIVTEST'
        method: 'POST'
        bearerToken: ${{ secrets.PIH_BAMBOO_API_KEY }}
        customHeaders: '{"Accept": "application/json"}'
        retry: 10
        retryWait: 60000

    - name: Deploy to zl-ci
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://bamboo-ci.pih-emr.org/rest/api/latest/queue/OMRS-DEPLOYZLCI'
        method: 'POST'
        bearerToken: ${{ secrets.PIH_BAMBOO_API_KEY }}
        customHeaders: '{"Accept": "application/json"}'
        retry: 10
        retryWait: 60000
